version: '3.8'

services:
  frontend:
    build: 
      context: ./web
      dockerfile: Dockerfile.web
    ports:
      - "8811:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8812/api
    depends_on:
      - backend

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "8812:8000"
    env_file:
      - ./api/.env